language: python
python:
    - "2.7"
    - "3.5"

sudo: false

compiler:
    - gcc
before_install:
    - cd "${HOME}"
    - nvm install v6
    - npm install -g npm
    - git clone git://github.com/girder/girder
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.2.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - cd "${HOME}"
    - curl -L "http://cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - ln -s "${HOME}/girder/package.json" "${TRAVIS_BUILD_DIR}/.."  # for eslint config
    - cd "${HOME}/girder/plugins"
    - ln -s "${TRAVIS_BUILD_DIR}" covalic
install:
    - cd "${HOME}/girder"
    - pip install -e .[thumbnails,worker]
    - pip install -U -r requirements-dev.txt
    - girder-install web --dev --plugins=covalic
script:
    - mkdir _build
    - cd _build
    - cmake -DRUN_CORE_TESTS:BOOL=OFF -DBUILD_JAVASCRIPT_TESTS:BOOL=OFF -DTEST_PLUGINS:STRING=covalic -DPYTHON_COVERAGE:BOOL=ON -DCOVERAGE_MINIMUM_PASS:STRING=4 -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} "${HOME}/girder"
    - ctest -V -j3
