name: COVALIC Challenges
description: An application for hosting grand challenges.
version: 0.1.0
dependencies:
    - gravatar
    - worker
    - thumbnails
webpack:
  main:
    plugin: web_client/main.js
    covalic: web_external/main.js
npm:
  dependencies:
    bootstrap-3-typeahead: ^4.0.2
