---
- name: give ownership of /opt/covalic to vagrant user
  file: path=/opt/covalic
        owner=vagrant
        group=vagrant
        mode=0775
        state=directory
        recurse=no
  become: yes

- name: install curl
  apt: pkg=curl state=present
  become: yes
  tags: common
