---
- name: Update apt cache and install docker prerequisites
  apt: update_cache=yes name={{ item }} state=present
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags: celery

- name: Add GPG key for docker
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  tags:
    - celery
    - deploy-update

- name: Add docker PPA
  become: yes
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  tags:
    - celery
    - deploy-update

- name: Install worker dependencies
  become: yes
  apt: update-cache=yes name={{ item }} state=present
  with_items:
    - libffi-dev
    - libssl-dev
    - python-pip
    - python-dev
    - git
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libpng-dev
    - docker-ce
  tags:
    - celery
    - deploy-update

- name: Start docker daemon
  service: name=docker state=started enabled=yes
  become: yes
  tags:
    - celery
    - deploy-update

- name: Clone girder_worker
  become: yes
  git:
      repo: git://github.com/girder/girder_worker.git
      dest: /opt/girder_worker
      accept_hostkey: yes
      force: yes
      version: "{{ girder_worker_version }}"
  tags:
    - celery
    - deploy-update

- name: Install girder_worker using pip editable install
  command: pip install -e "/opt/girder_worker[girder_io,docker]"
  become: yes
  tags:
    - celery
    - deploy-update

- name: Create local worker config file
  become: yes
  template:
    src: worker.local.cfg.j2
    dest: /opt/girder_worker/girder_worker/worker.local.cfg
    mode: 0644
    owner: "{{worker_exec_user}}"
    group: "{{worker_exec_group}}"
  tags:
    - celery
    - deploy-update

- name: Change ownership of worker to correct user
  become: yes
  file:
    dest: /opt/girder_worker
    owner: "{{worker_exec_user}}"
    group: "{{worker_exec_group}}"
    state: directory
    recurse: yes
  tags:
    - celery
    - deploy-update

- name: Create Docker group
  group: name=docker state=present
  tags: celery

- name: Add worker user to Docker group
  user: shell=/bin/bash
        name={{worker_exec_user}}
        groups=docker
        append=yes
  become: yes
  tags: celery

- name: Restart docker daemon
  service: name=docker state=restarted enabled=yes
  become: yes
  tags:
    - celery
    - deploy-update

- name: Install girder worker as a service
  template:
      src: girder_worker.service.j2
      dest: /lib/systemd/system/girder_worker.service
      mode: 644
      owner: root
  become: yes
  tags: celery

- name: Restart celery worker as a service
  systemd: name=girder_worker state=restarted enabled=yes daemon_reload=yes
  become: yes
  tags:
    - celery
    - deploy-update
