---
- name: MongoDB | Fetch GPG key
  become: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  tags: mongodb

- name: MongoDB | Add 10 gen repository
  become: yes
  shell:
    echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  tags: mongodb

- name: MongoDB | Install latest mongodb
  become: yes
  apt: pkg={{ item }} update-cache=yes
  with_items:
    - mongodb-org
    - python-pip
  tags: mongodb

- name: Get the most recent version of pip
  pip: name=pip extra_args="-U"
  become: yes
  tags:
    - mongodb
    - deploy-update

- name: Get boto pip package
  pip: name=boto version=2.39.0
  become: yes
  tags:
    - mongodb
    - deploy-update

# TODO this will have to be redone for clustered mongo
# change the mongodb from listening only on the local ip to the internal ip
- name: Make mongo listen on private IP interface
  become: yes
  lineinfile:
    dest: /etc/mongod.conf
    state: present
    regexp: '  bindIp:(.*)'
    line: "  bindIp: {{ mongo_private_ip }}"
  tags:
    - mongodb
    - rewire

- name: Ensure db directory exists
  become: yes
  file:
    path: "{{ mongo_dbpath }}"
    state: directory
    owner: mongodb
    group: mongodb
  tags:
    - mongodb
    - rewire

- name: Run mongo daemon
  become: yes
  systemd: name=mongod state=restarted
  tags:
    - mongodb
    - rewire

- name: Wait for Mongo startup
  wait_for:
    port: 27017
    timeout: 15
  tags:
    - mongodb
    - deploy-update
    - rewire

- name: Install backup_db.sh script
  become: yes
  template:
    dest: /home/ubuntu/backup_db.sh
    src: backup_db.sh
    mode: 0755
  tags:
    - mongodb
    - deploy-update

- name: Install S3 upload script
  become: yes
  template:
    dest: /home/ubuntu/upload_to_s3.py
    src: upload_to_s3.py
  tags:
    - mongodb
    - deploy-update
