---
- name: Install rabbitmq system package
  become: yes
  apt: update-cache=yes name=rabbitmq-server state=present
  tags:
    - mq
    - deploy-update

- name: Enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
  become: yes
  tags: mq
