---
- hosts: all
  tasks:
    - name: Require pod to be defined
      fail: msg="You did not define a pod name to manage all resources. Example definition | -e 'pod=dev'"
      when: pod is not defined
      tags:
        - mongodb
        - girder
        - girder-update
        - girder-assetstore
        - celery
        - mq
        - rewire

# Mongo needs to be running before Girder or else Girder fails to start
- name: Mongo
  user: ubuntu
  hosts: tag_mongodb_true:&tag_pod_{{pod}}
  gather_facts: false
  roles:
    - common
    - mongodb

# Message queue should be running before Girder and the worker
- name: Message queue
  user: ubuntu
  hosts: tag_mq_true:&tag_pod_{{pod}}
  gather_facts: false
  roles:
    - common
    - mq

- name: Celery
  user: ubuntu
  hosts: tag_worker_true:&tag_pod_{{pod}}
  gather_facts: false
  roles:
    - common
    - celery

- name: Girder
  user: ubuntu
  hosts: tag_girder_true:&tag_pod_{{pod}}
  gather_facts: false
  vars:
    girder_admin_user: covalic
    girder_admin_email: covalic-aws@kitware.com
    girder_socket_host: localhost
    girder_socket_port: 8080
    girder_plugins:
      - covalic
      - oauth
    girder_celery_user: celery
    girder_celery_email: covalic-celery@kitware.com
  vars_files:
    - pod_static_vars/{{pod}}_s3_assetstore.yml
    - pod_static_vars/{{pod}}_girder_passwords.yml
    - pod_static_vars/prod_cert.yml
    - pod_static_vars/prod_key.yml
  roles:
    - common
    - girder
