---
- hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install python2 for ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
      become: true

    - name: Gathering Facts
      setup:
      become: true

  roles:
    - vagrant
    - mongodb
    - girder
    - mq
    - celery
  vars:
    pod: dev  # girder config actually requires pod to be set
    vagrant: true
    girder_admin_user: covalic
    girder_admin_email: covalic@kitware.com
    girder_admin_password: covalic
    girder_socket_host: localhost
    girder_socket_port: 8080
    girder_exec_user: vagrant
    girder_exec_group: vagrant
    girder_plugins:
      - covalic
    girder_celery_user: celery
    girder_celery_email: covalic-celery@kitware.com
    girder_celery_password: celery
    girder_root: /opt/covalic/girder
    girder_assetstore_type: filesystem
    girder_assetstore_name: local_fs
    girder_assetstore_local_fs: true
    worker_exec_user: vagrant
    worker_exec_group: vagrant
    mongo_dbpath: /data/db
